### ISSUE TITLE
My suggestion: give up this unrealistic idea

### ISSUE THREAD

**Issue by BrushXue** [apjanke/homebrew-openfoam#5] opened 2022-02-13 01:12 UTC
As far as I know:
1. You need to compile it in a case-sensitive volume, which seems like impossible in homebrew.
2. The `scotch` in homebrew won't work, unless they agree to remove `-DSCOTCH_PTHREAD` flag.
3. `zsh` support is still buggy, see https://github.com/mrklein/openfoam-os-x/issues/60
4. `CGAL` support is also buggy, see https://github.com/mrklein/openfoam-os-x/issues/64
5. Takes too long time to compile and homebrew guys might be unhappy about it.

**Comment by gerlero** [comment] 2022-02-14 21:06
Hi! Another Mac & OpenFOAM user here who's also been attempting something like this. From what I've tried, I have to agree with your points 1 & 4. OTOH, I've managed to successfully compile and run v2112 using Homebrew's `scotch`. On the `zsh` front, I haven't run into any major issues (yet).

With what I got, I took a slightly different approach and have managed to package OpenFOAM into a cask (https://github.com/gerlero/openfoam2112-app), which contains a (read-only) case-sensitive DMG where OpenFOAM has been built from source. I'm using the unpatched v2112 sources plus all dependencies from Homebrew (except of course no `CGAL`).

Back to your first point, I think if there were a way to create the DMG within Homebrew's formula build sandbox, I guess that could make for a viable (though not sure if up to `homebrew-core` standards) formula; but for now I'm quite content with having been able to turn OpenFOAM into an installable cask. In any case, I wanted to let you and @apjanke know about my project (and I'm open to contributions).

**Comment by BrushXue** [comment] 2022-02-14 21:41
>  I've managed to successfully compile and run v2112 using Homebrew's `scotch`. 

I know scotch is OK but have you tried any `pt-scotch` case, like the motorbike case?

> On the `zsh` front, I haven't run into any major issues (yet).

Sometimes when running scripts, `zsh` can't load OpenFOAM libraries. Happened on both my x86 hackintosh and M1.

**Comment by gerlero** [comment] 2022-02-15 15:24
> I know scotch is OK but have you tried any `pt-scotch` case, like the motorbike case?

I've tried it now: `snappyHexMesh` seems to get stuck forever... is that what normally happens with Homebrew's `scotch`? I don't have a strict requirement to use Homebrew's `scotch` if your repo (and/or mrklein's) has a fix for that.

> Sometimes when running scripts, `zsh` can't load OpenFOAM libraries. Happened on both my x86 hackintosh and M1.

That unfortunately happens to me with `bash` as well (even the newer `bash` from Homebrew). I think it's caused by https://develop.openfoam.com/Development/openfoam/-/issues/1661 and https://develop.openfoam.com/Development/openfoam/-/issues/1664. I haven't tried a successful workaround yet.

**Comment by BrushXue** [comment] 2022-02-15 15:52
> I don't have a strict requirement to use Homebrew's `scotch` if your repo (and/or mrklein's) has a fix for that.

The fix is very simple: drop `-DSCOTCH_PTHREAD` flag. https://github.com/BrushXue/OpenFOAM-AppleM1/blob/c7fc31aba8ad1779116d94b73ad2e55d853ad5de/scotch.rb#L41
Is there any way to automatically follow and patch the latest homebrew script?
> I think it's caused by https://develop.openfoam.com/Development/openfoam/-/issues/1661 and https://develop.openfoam.com/Development/openfoam/-/issues/1664.

Now I know why it's not happening all the time. Sometimes when I play around my hackintosh I turn off SIP. Didn't even think about it.

**Comment by gerlero** [comment] 2022-02-15 21:39
> The fix is very simple: drop `-DSCOTCH_PTHREAD` flag. https://github.com/BrushXue/OpenFOAM-AppleM1/blob/c7fc31aba8ad1779116d94b73ad2e55d853ad5de/scotch.rb#L41 Is there any way to automatically follow and patch the latest homebrew script?

I see you proposed this change to `homebrew-core`, but it was never merged.. are they not in favor of making this change in core?

> Now I know why it's not happening all the time. Sometimes when I play around my hackintosh I turn off SIP. Didn't even think about it.

Right now I'm trying a quick fix/workaround (https://github.com/gerlero/openfoam2112-app/pull/6).

**Comment by BrushXue** [comment] 2022-02-15 22:15
> I see you proposed this change to `homebrew-core`, but it was never merged.. are they not in favor of making this change in core?


I proposed this change in the PR. But homebrew maintainers said it's too old and shouldn't be enabled unless more people complain about it. So maybe if you start an issue they'll listen.

**Comment by apjanke** [comment] 2022-02-19 10:00
So, after learning more about the OpenFOAM build & install process and thinking about this some more, I'm afraid I'm in agreement with @BrushXue here: the case-sensitive-volume issue seems like pretty much a showstopper in terms of working with core Homebrew or most user Homebrew installations, the Scotch pthreads thing is also a problem I don't have an answer for (aside from just making a custom scotch formula), and hoo boy that compile time. Plus, there's just a lot of outstanding smaller issues in terms of getting this to compile and install "cleanly" on macOS (or, IMHO, "standard" Unix in general), and upstream doesn't seem enthusiastic about supporting Mac in this way. And if there's no hope of getting this in to Homebrew core where people can make use of binary bottles, there's a lot less of a win scenario here.

FWIW, I think the zsh issue is totally tractable: The usual way to do zsh support like this isn't to ship serious zsh support in the main package itself, but to create a separate third-party whatever-szh-support project, like openfoam-zsh-support, and all the zsh users of openfoam install that. Most software makers are not zsh experts, and vice versa, and it's fine to have "bindings" and shell support for a tool be a separate project, IMHO. Mostly works just fine in practice.

I'm afraid I don't have the spare juice to spend on this effort, given these constraints. So I'm gonna throw in the towel here. Maybe what's in this repo will be useful to somebody else who's more ambitious here. Feel free to copy or fork it, or if you want, I'll just hand over ownership of the repo to someone who'll actually do something with it.

@gerlero feel free to gank any code here you find useful for your project, with my blessing, and godspeed! FWIW, I think your cask approach is probably a better idea than what I've got here.

Sorry folks! This was my bad for getting too excited too soon.

**Closed as completed** 2022-03-16 00:48 UTC
